// Career roadmaps for 5 domains
const roadmaps = {
    'Engineering': {
        key: 'technology',
        title: 'Engineering / B.Tech',
        icon: '🤖',
        color: '#6366f1',
        tagline: 'Apply science and math to design systems, solve problems, and build the future',
        requiredSubjects: ['Mathematics (Strict Requirement)', 'Physics', 'Chemistry'],
        entranceExams: ['JEE Main', 'JEE Advanced', 'BITSAT', 'State Level CETs'],
        degreeDuration: '4 Years (B.E. / B.Tech)',
        topColleges: ['IITs', 'NITs', 'BITS', 'Top State Colleges', 'Specialized Universities'],
        salaryRange: '₹3–8 LPA (entry-level core / software roles)',
        careerGrowth: 'Graduate Engineer Trainee → Senior Engineer → R&D / Management / Higher Studies (MS/MBA)',
        milestones: [
            { year: 'Now', title: 'Exploration Phase', desc: 'Solve real-world problems, build basic coding/electronics projects, separate interest from external pressure' },
            { year: 'After 10th', title: 'Subject Foundation', desc: 'Choose Science (PCM). Focus strongly on grasping concepts in Math and Physics rather than rote learning' },
            { year: 'After 12th', title: 'Admissions', desc: 'Clear national/state entrance exams. College quality depends heavily on peer learning, faculty, and labs' },
            { year: 'Engineering', title: 'Core Education', desc: 'Intensive coursework, labs, and projects. Requires building analytical and system-level problem solving skills' },
            { year: 'College', title: 'Skill Development', desc: 'Develop tools/software proficiency, understanding of constraints, teamwork, and independent learning abilities' },
            { year: 'Professional', title: 'Broad Career Exits', desc: 'Enter core tech, IT, or transition to management/entrepreneurship. Continuous skill upgrading is essential' },
        ],
    },
    'Doctor (Medical Profession)': {
        key: 'medical',
        title: 'Doctor (Medical Profession)',
        icon: '🏥',
        color: '#10b981',
        tagline: 'A profession of service, science, and accountability',
        requiredSubjects: ['Biology (Strict Requirement)', 'Chemistry', 'Physics'],
        entranceExams: ['NEET for MBBS Admission (Extremely Demanding)'],
        degreeDuration: '10–15 Years (MBBS + Internship + PG Specialization)',
        topColleges: ['Government Colleges (High competition)', 'Private Colleges'],
        salaryRange: '₹4–25+ LPA (junior doctor to specialist)',
        careerGrowth: 'Intern → Junior Doctor → PG Specialization (MD/MS) → Specialist / Surgeon',
        milestones: [
            { year: 'Now', title: 'Exploration Phase', desc: 'Talk to practicing doctors, observe hospital environments, and reflect on stress tolerance before committing' },
            { year: 'After 10th', title: 'Subject Foundation', desc: 'Choose Science (PCB). Preparation begins for medical entrance exams alongside school studies' },
            { year: 'After 12th', title: 'Entrance & MBBS', desc: 'Clear entrance exams to enter MBBS. The program involves basic medical sciences and clinical hospital rotations' },
            { year: 'MBBS End', title: 'Internship', desc: 'Complete mandatory internship. Training shifts fully to hospital exposure with emotionally demanding situations' },
            { year: 'Post MBBS', title: 'Specialization / PG', desc: 'Pursue MD/MS. Real career direction forms here (e.g., Surgery, Pediatrics, General Medicine)' },
            { year: 'Professional', title: 'Lifelong Learning', desc: 'Work as a Specialist, Surgeon, Researcher, or in Healthcare Administration. Mental endurance is fully tested' },
        ],
    },
    'Law': {
        key: 'law',
        title: 'Law',
        icon: '⚖️',
        color: '#f59e0b',
        tagline: 'Thinking-intensive profession interpreting statutes, advising, and balancing rights',
        requiredSubjects: ['Any Stream (Reading & Critical Thinking help)'],
        entranceExams: ['CLAT / National or University-specific Tests', '3-year LLB after graduation'],
        degreeDuration: '5 Years (Integrated) or 3 Years (Post-Graduation)',
        topColleges: ['National Law Universities (NLUs)', 'State Universities', 'Private Law Colleges'],
        salaryRange: '₹1.5–8+ LPA (entry-level litigation to corporate law)',
        careerGrowth: 'Junior Advocate / Legal Associate → Independent Practice / Corporate Leadership / Judiciary',
        milestones: [
            { year: 'Now', title: 'Exploration Phase', desc: 'Read legal news, visit courts, talk to law students. Develop comfort with extensive reading and argumentation' },
            { year: 'After 10th', title: 'Subject Foundation', desc: 'Choose Arts, Commerce, or Science in 11th–12th. Build reading, writing, and comprehension skills' },
            { year: 'After 12th', title: '5-Year Law Programs', desc: 'Formal entry via BA/BBA/BSc LLB. Covers Constitutional, Criminal, and Commercial Law' },
            { year: 'Law School', title: 'Academics & Exposure', desc: 'Learn through extensive reading, analyzing judgements, debates, and interpreting texts realistically' },
            { year: 'Internships', title: 'Practical Experience', desc: 'Internships and court exposure are critical. Learning often depends on seniors, not textbooks' },
            { year: 'Professional', title: 'Career Progression', desc: 'Start in litigation (slow initial growth) or corporate law. Growth requires deep patience and absolute integrity' },
        ],
    },
    'Business / BBA-MBA': {
        key: 'business',
        title: 'Business / BBA-MBA',
        icon: '💼',
        color: '#8b5cf6',
        tagline: 'Lead markets, build empires',
        requiredSubjects: ['Economics', 'Mathematics', 'Accountancy', 'Business Studies', 'Statistics'],
        entranceExams: ['CAT', 'XAT', 'SNAP', 'IPU CET', 'NMIMS CET (for BBA)'],
        degreeDuration: '3 Years (BBA) + 2 Years (MBA)',
        topColleges: ['IIM Ahmedabad', 'IIM Bangalore', 'IIM Calcutta', 'XLRI Jamshedpur', 'SP Jain Mumbai'],
        salaryRange: '₹6–80 LPA (fresher to senior management)',
        careerGrowth: 'Management Trainee → Business Analyst → Manager → General Manager → CEO / Entrepreneur',
        milestones: [
            { year: 'Now', title: 'Foundation', desc: 'Build financial literacy, read business news (ET, Mint)' },
            { year: 'Year 1', title: 'BBA Entrance', desc: 'Prepare for IPU CET, NMIMS — aptitude + GK' },
            { year: 'Year 1-3', title: 'BBA Program', desc: 'Marketing, Finance, Operations, HR fundamentals' },
            { year: 'Year 2-3', title: 'Internships', desc: 'Intern at startups, MNCs (consult, finance, marketing)' },
            { year: 'Year 4-5', title: 'CAT + MBA', desc: 'Target CAT 99%ile for IIMs, XAT for XLRI' },
            { year: 'Post MBA', title: 'Leadership', desc: 'Consulting (McKinsey, BCG), Banking, or Start your own venture' },
        ],
    },
    'Multimedia / Digital Media': {
        key: 'design',
        title: 'Multimedia / Digital Media',
        icon: '🎨',
        color: '#ec4899',
        tagline: 'Communicate visually and structurally through images, video, audio, and interactive media',
        requiredSubjects: ['Any Stream (Skill matters over background)'],
        entranceExams: ['Portfolio Based', 'Institute-specific Extrance Exams'],
        degreeDuration: 'Short-term Certificate to 3-4 Year Degree Programs',
        topColleges: ['Design Institutes', 'Media Colleges', 'Private Academies'],
        salaryRange: '₹2.5–6 LPA (entry-level graphic/video to UI roles)',
        careerGrowth: 'Graphic Designer / Editor / Animator → Senior Lead → Creative Director / Freelancer',
        milestones: [
            { year: 'Now', title: 'Exploration Phase', desc: 'Create/edit consistently. Build small projects, take feedback seriously, and test your comfort with long screen hours' },
            { year: 'After 10th', title: 'Early Discovery', desc: 'Take certificate courses, start learning basics of editing, graphics, or animation to find your fit' },
            { year: 'After 12th', title: 'Degree Programs', desc: 'Pursue visual communication or design degrees. Deep dive into workflows, storytelling, and client demands' },
            { year: 'College', title: 'Skill Development', desc: 'Learn software proficiencies, design fundamentals, and how to balance creativity with constraints' },
            { year: 'Portfolio', title: 'Project Focus', desc: 'Building a strong portfolio through projects heavily outweighs getting a degree. Constant tool upgrading is required' },
            { year: 'Professional', title: 'Career Growth', desc: 'Enter as Graphic Designer, Editor, or UI/UX Assistant. Growth is entirely self-driven and reputation-based' },
        ],
    },
    'Fashion Designing': {
        key: 'fashion',
        title: 'Fashion Designing',
        icon: '👗', // Using a dress icon for fashion
        color: '#f43f5e', // Rose
        tagline: 'Shape your dream into an art form and lifestyle',
        requiredSubjects: ['Fine Arts', 'Design', 'Business Studies', 'English', 'Maths'],
        entranceExams: ['NIFT Entrance Test', 'Pearl Academy Admission Test', 'SET Design'],
        degreeDuration: 'Diploma (1-3 Years) or Degree (3-4 Years)',
        topColleges: ['National Institute of Fashion Technology (NIFT)', 'Pearl Academy', 'Symbiosis Institute of Design (SID)'],
        salaryRange: '₹3–12 LPA (fresher to experienced)',
        careerGrowth: 'Merchandiser / Stylist → Fashion Designer → Creative Director / Brand Owner',
        milestones: [
            { year: 'Now', title: 'Develop Skills', desc: 'Start sketching, illustrating, and learning basics of sewing and textiles' },
            { year: '11th/12th', title: 'Choose Stream', desc: 'Opt for Arts (creativity) or Commerce (business skills) with Fine Arts' },
            { year: 'After 10th', title: 'Diploma Option', desc: 'Diploma in Fashion/Apparel/Textile Design to start early' },
            { year: 'Post 12th', title: 'Degree prep', desc: 'Clear NIFT Entrance or Pearl Academy Test for top colleges' },
            { year: 'College', title: 'Build Portfolio', desc: 'Create a unique portfolio highlighting individuality; pursue internships' },
            { year: 'Professional', title: 'Career Paths', desc: 'Work as Designer, Stylist, Merchandiser or explore Sustainable/Digital Fashion' },
        ],
    },
    'B.Arch / Architecture': {
        key: 'architecture',
        title: 'Architecture (B.Arch)',
        icon: '🏛️',
        color: '#0ea5e9',
        tagline: 'A field where design meets responsibility, planning safe and meaningful spaces',
        requiredSubjects: ['Physics', 'Chemistry', 'Mathematics (Strict Requirement)'],
        entranceExams: ['National Level Architecture Entrance Exams', 'Aptitude Tests'],
        degreeDuration: '5 Years (Bachelor of Architecture)',
        topColleges: ['Government & Public Institutes', 'Accredited Private/Autonomous Colleges'],
        salaryRange: '₹2.5–5 LPA (entry-level Junior Architect or Design Assistant)',
        careerGrowth: 'Junior Architect / Architectural Assistant → Site Coordinator → Independent Practice / Specialized Roles',
        milestones: [
            { year: 'Now', title: 'Exploration Phase', desc: 'Observe how buildings and spaces are designed, visit architecture colleges, and practice sketching everyday spaces' },
            { year: 'After 10th', title: 'Preparation & Curiosity', desc: 'Choose Science stream (PCM) in 11th-12th. Develop skills in drawing, geometry, and observation' },
            { year: 'After 12th', title: 'Entrance & Admission', desc: 'Clear architecture entrance exams and aptitude tests after completing 12th with PCM' },
            { year: 'B.Arch', title: 'Intensive Education', desc: '5-year professional degree involving long studio hours, frequent design critiques, and iterative design' },
            { year: 'College', title: 'Core Learnings', desc: 'Learn Building Materials, Structural Systems, Architecture History, Sustainable Design, and Urban Planning' },
            { year: 'Professional', title: 'Early Career Options', desc: 'Start as Junior Architect or Design Support. It is a slow-burn career focused on long-term value.' },
        ],
    },
    'Chartered Accountancy': {
        key: 'ca',
        title: 'Chartered Accountancy (CA)',
        icon: '📈',
        color: '#eab308',
        tagline: 'A profession built on trust, accuracy, and responsibility that demands long-term focus',
        requiredSubjects: ['Any Stream (Commerce Preferred)', 'Accountancy', 'Economics', 'Business Studies'],
        entranceExams: ['CA Foundation (Official starting point)'],
        degreeDuration: 'Several Years (Self-Study Heavy)',
        topColleges: ['ICAI (Institute of Chartered Accountants of India)'],
        salaryRange: '₹7–30+ LPA (entry-level to experienced/leadership)',
        careerGrowth: 'CA in Practice/Auditor → Financial Controller → CFO / Business Advisory / Entrepreneurship',
        milestones: [
            { year: 'Now', title: 'Exploration Phase', desc: 'Observe how finance professionals work, study basic accounting, and check your discipline for long studying hours' },
            { year: 'After 10th', title: 'Subject Foundation', desc: 'Usually choose Commerce stream. Focus strongly on Accountancy, Economics, and Business Studies' },
            { year: 'After 12th', title: 'CA Foundation', desc: 'The official starting point of the CA journey covering Accounting, Law, Economics, and Maths' },
            { year: 'CA Inter', title: 'Intermediate Level', desc: 'Advanced accounting, Taxation, Auditing, and Financial Management' },
            { year: 'Final & Training', title: 'CA Final & Articleship', desc: 'Complete mandatory practical training alongside high-level professional subjects for real-world application' },
            { year: 'Professional', title: 'Broad Career Exits', desc: 'Enter auditing, tax consulting, corporate finance, or independent practice. Success requires strict resilience.' },
        ],
    },
    'Chef / Culinary Arts': {
        key: 'chef',
        title: 'Chef / Culinary Arts',
        icon: '👨‍🍳',
        color: '#f97316',
        tagline: 'High-pressure, team-driven food preparation demanding extreme discipline and consistency',
        requiredSubjects: ['Any Stream (Discipline & practical learning)'],
        entranceExams: ['Diploma Admissions', 'Degree/Hotel Management Entrances'],
        degreeDuration: 'Certificate (Months) to 3-4 Years (Culinary Degree)',
        topColleges: ['Hotel Management Institutes', 'Culinary Schools', 'Food Craft Institutes'],
        salaryRange: '₹1.8–4 LPA (entry-level commis or kitchen assistant)',
        careerGrowth: 'Commis Chef → Chef de Partie → Sous Chef → Head Chef / Restaurant Owner',
        milestones: [
            { year: 'Now', title: 'Exploration Phase', desc: 'Work part-time in a kitchen, observe professional setups, cook repetitively (not occasionally), and test your stamina' },
            { year: 'After 10th', title: 'Early Discovery', desc: 'Enroll in certificate courses and learn basic knife work, kitchen safety, and hygiene standards' },
            { year: 'After 12th', title: 'Formal Training', desc: 'Pursue Culinary Arts/Hotel Management degrees for internships and deeper industry exposure' },
            { year: 'Kitchen', title: 'Skill Development', desc: 'Learn consistency, timing, basic food preparation, obedience to systems, and physical stamina' },
            { year: 'Training', title: 'Reality Check', desc: 'Experience long standing hours, hot environments, strict hierarchies, and limited creative freedom early on' },
            { year: 'Professional', title: 'Career Progression', desc: 'Start as Commis Chef or Line Cook. Long-term progression to Sous/Head Chef demands persistence and skill mastery' },
        ],
    },
    'Hotel Management': {
        key: 'hotel',
        title: 'Hotel Management',
        icon: '🏨',
        color: '#06b6d4',
        tagline: 'Lead the hospitality industry globally',
        requiredSubjects: ['English', 'Any Stream', 'Communication Skills'],
        entranceExams: ['NCHMCT JEE', 'UGAT', 'IIHM eCHAT'],
        degreeDuration: '3-4 Years (B.Sc Hospitality & Hotel Administration)',
        topColleges: ['IHM Pusa', 'IHM Mumbai', 'IHM Aurangabad', 'Christ University'],
        salaryRange: '₹3–18 LPA (Trainee to General Manager)',
        careerGrowth: 'Management Trainee → Duty Manager → Front Office/F&B Director → General Manager',
        milestones: [
            { year: 'Now', title: 'Foundation', desc: 'Work on communication, grooming, and interpersonal skills' },
            { year: 'Year 1', title: 'Entrance Prep', desc: 'Clear NCHMCT JEE for top government IHMs' },
            { year: 'Year 1-2', title: 'Core Departments', desc: 'Learn Front Office, F&B Service, Food Production, and Housekeeping' },
            { year: 'Year 2-3', title: 'Industrial Training', desc: '4-6 months mandatory internship across all 4 major departments in a 5-star property' },
            { year: 'Year 4', title: 'Specialization & Placements', desc: 'Choose a major and sit for Management Trainee programs (Taj, Oberoi, Marriott)' },
            { year: 'Professional', title: 'Career Growth', desc: 'Fast-track to management in hospitality, cruise lines, or luxury retail' },
        ],
    },
    'Pharmacy / B.Pharm': {
        key: 'pharma',
        title: 'Pharmacy (B.Pharm)',
        icon: '💊',
        color: '#14b8a6',
        tagline: 'Bridging chemistry and human health',
        requiredSubjects: ['Chemistry', 'Biology', 'Physics', 'Mathematics'],
        entranceExams: ['NEET', 'MHT-CET', 'CUET', 'BITSAT'],
        degreeDuration: '4 Years (B.Pharm) + optional 2 Years (M.Pharm)',
        topColleges: ['NIPER', 'Jamia Hamdard', 'BITS Pilani', 'Manipal College of Pharmaceutical Sciences'],
        salaryRange: '₹3–15 LPA (Fresher to R&D Scientist)',
        careerGrowth: 'Pharmacist/Analyst → Quality Controller → Regulatory Affairs / R&D Manager → Director',
        milestones: [
            { year: 'Now', title: 'Foundation', desc: 'Master Chemistry and Biology fundamentals' },
            { year: 'Year 1', title: 'Admissions', desc: 'Score well in state CETs, CUET, or NEET for top pharmacy colleges' },
            { year: 'Year 1-2', title: 'Core Pharmacy', desc: 'Pharmaceutics, Human Anatomy, Pharmaceutical Chemistry' },
            { year: 'Year 3-4', title: 'Advanced Pharma', desc: 'Pharmacology, Industrial Pharmacy, and Clinical Pharmacy' },
            { year: 'Year 4', title: 'Internship & Research', desc: 'Complete industry training in manufacturing or QA/QC labs' },
            { year: 'Professional', title: 'Career Paths', desc: 'Join pharma R&D (Sun Pharma, Cipla), clinical research, or start a pharmacy business' },
        ],
    },
    'Master of Business Administration (MBA)': {
        key: 'mba',
        title: 'MBA (Master of Business Administration)',
        icon: '📊',
        color: '#6366f1', // Indogo color to match corporate theme
        tagline: 'A strategic training ground for leadership and decision-making',
        requiredSubjects: ['Any Undergraduate Degree', 'Analytical Skills', 'General Awareness'],
        entranceExams: ['CAT', 'XAT', 'GMAT', 'SNAP', 'NMAT'],
        degreeDuration: '2 Years (Post-Graduation)',
        topColleges: ['IIMs (A, B, C, L, K, I)', 'ISB Hyderabad', 'XLRI Jamshedpur', 'FMS Delhi', 'SPJIMR Mumbai'],
        salaryRange: '₹6–20+ LPA (entry to mid-level depending on college tier)',
        careerGrowth: 'Analyst/Trainee → Manager → Director / VP → C-Suite Executive (CEO/COO)',
        milestones: [
            { year: 'Now', title: 'Exploration Phase', desc: 'Observe business operations, read about startups/corporate world, build leadership vs execution preferences' },
            { year: 'UG Choice', title: 'Undergraduate Base', desc: 'Pursue Any Degree (Engineering/Commerce/Arts/Science) - MBA values diverse backgrounds' },
            { year: 'During UG', title: 'Skill Building', desc: 'Focus on communication, problem-structuring, teamwork, and taking leadership initiatives' },
            { year: 'Post UG', title: 'Entrance Prep & Work Exp', desc: 'Prepare for CAT/XAT/GMAT. 1-3 years of work experience is often highly beneficial before MBA' },
            { year: 'MBA Prog', title: 'Core Competencies', desc: 'Learn Strategy, Marketing, Finance, HR, Operations, and Business Analytics through case studies' },
            { year: 'Professional', title: 'Career Trajectory', desc: 'Enter as Management Consultant, Product Manager, Strategy Manager, or dive into Entrepreneurship' },
        ],
    },
};

module.exports = roadmaps;
