// Adaptive Psychometric questions
const questions = [
    // --- 10TH (Interest & Aptitude Exploration) ---
    // Analytical
    { id: 101, tier: '10th', domain: 'analytical', question: 'When solving a difficult math or puzzle problem, how do you feel?', options: [{ label: 'A', text: 'Excited by the challenge', score: 3 }, { label: 'B', text: 'Okay, but I prefer English', score: 1 }, { label: 'C', text: 'Frustrated easily', score: 0 }, { label: 'D', text: 'I push through step-by-step', score: 2 }] },
    { id: 102, tier: '10th', domain: 'analytical', question: 'If a gadget breaks at home, what is your instinct?', options: [{ label: 'A', text: 'Open it up and see how it works inside', score: 3 }, { label: 'B', text: 'Search YouTube for a fix', score: 2 }, { label: 'C', text: 'Wait for someone else to fix it', score: 0 }, { label: 'D', text: 'Complain about it', score: 0 }] },
    // Creativity
    { id: 103, tier: '10th', domain: 'creativity', question: 'For a school project, which part do you volunteer for?', options: [{ label: 'A', text: 'Designing the charts and visuals', score: 3 }, { label: 'B', text: 'Presenting the final concept', score: 2 }, { label: 'C', text: 'Doing the core research', score: 1 }, { label: 'D', text: 'Organizing the meeting times', score: 0 }] },
    { id: 104, tier: '10th', domain: 'creativity', question: 'When you have free time, you prefer to:', options: [{ label: 'A', text: 'Sketch, write stories, or edit videos', score: 3 }, { label: 'B', text: 'Play logical games like Chess/Sudoku', score: 0 }, { label: 'C', text: 'Read about real-world events', score: 1 }, { label: 'D', text: 'Hang out and debate politics', score: 0 }] },
    // Leadership
    { id: 105, tier: '10th', domain: 'leadership', question: 'If there is chaos in the classroom because the teacher is late, you:', options: [{ label: 'A', text: 'Stand up and tell everyone to quiet down', score: 3 }, { label: 'B', text: 'Help your friends study while waiting', score: 2 }, { label: 'C', text: 'Join the chaos', score: 0 }, { label: 'D', text: 'Sit quietly and read', score: 1 }] },
    { id: 106, tier: '10th', domain: 'leadership', question: 'In group sports or games, you usually:', options: [{ label: 'A', text: 'Become the captain or call the shots', score: 3 }, { label: 'B', text: 'Just follow the rules', score: 0 }, { label: 'C', text: 'Focus on your own technique', score: 1 }, { label: 'D', text: 'Ensure everyone gets a turn', score: 2 }] },
    // Medical
    { id: 107, tier: '10th', domain: 'medical', question: 'When learning Biology (like the human digestive system), you feel:', options: [{ label: 'A', text: 'Fascinated by how life works perfectly', score: 3 }, { label: 'B', text: 'Bored, I prefer Physics/Math', score: 0 }, { label: 'C', text: 'Nauseous when looking at anatomy', score: 0 }, { label: 'D', text: 'Curious enough to memorize it', score: 1 }] },
    { id: 108, tier: '10th', domain: 'medical', question: 'If a friend scrapes their knee badly at school, you:', options: [{ label: 'A', text: 'Immediately clean it and apply a bandage', score: 3 }, { label: 'B', text: 'Feel faint seeing blood', score: 0 }, { label: 'C', text: 'Call a teacher for help', score: 1 }, { label: 'D', text: 'Look up the best way to treat it online', score: 2 }] },
    // Business
    { id: 109, tier: '10th', domain: 'business', question: 'If your school hosted a charity fair, what would you do?', options: [{ label: 'A', text: 'Set up a stall selling snacks for max profit', score: 3 }, { label: 'B', text: 'Draw the posters for the fair', score: 0 }, { label: 'C', text: 'Manage the money box', score: 2 }, { label: 'D', text: 'Just visit as a customer', score: 0 }] },
    { id: 110, tier: '10th', domain: 'business', question: 'When you get pocket money, your first thought is usually:', options: [{ label: 'A', text: 'How can I double this by selling something?', score: 3 }, { label: 'B', text: 'Save it for the future', score: 2 }, { label: 'C', text: 'Spend it on games immediately', score: 0 }, { label: 'D', text: 'Buy art supplies or tech gadgets', score: 0 }] },

    // --- 11TH/12TH (Stream Suitability & Skill Inclination) ---
    // Analytical
    { id: 201, tier: '12th', domain: 'analytical', question: 'How do you approach heavy Calculus or tricky Physics numericals?', options: [{ label: 'A', text: 'I enjoy deriving the formulas and solving them', score: 3 }, { label: 'B', text: 'I struggle and prefer theory', score: 0 }, { label: 'C', text: 'I do them because I have to pass', score: 1 }, { label: 'D', text: 'I look for patterns to solve them faster', score: 2 }] },
    { id: 202, tier: '12th', domain: 'analytical', question: 'What is your perspective on coding/programming subjects?', options: [{ label: 'A', text: 'Fascinating — I love building logic', score: 3 }, { label: 'B', text: 'Intimidating, I hate syntax errors', score: 0 }, { label: 'C', text: 'Useful tool for future', score: 2 }, { label: 'D', text: 'Indifferent', score: 1 }] },
    // Creativity
    { id: 203, tier: '12th', domain: 'creativity', question: 'When analyzing literature or art in school, you:', options: [{ label: 'A', text: 'Create entirely new interpretations effortlessly', score: 3 }, { label: 'B', text: 'Just memorize what the teacher said', score: 0 }, { label: 'C', text: 'Try to understand the structural metrics', score: 1 }, { label: 'D', text: 'Enjoy imagining the scenes vividly', score: 2 }] },
    // Leadership
    { id: 204, tier: '12th', domain: 'leadership', question: 'Do you keep up with Current Affairs, Policy, or Law debates?', options: [{ label: 'A', text: 'Yes, I actively read news and debate them', score: 3 }, { label: 'B', text: 'I only read tech/science news', score: 0 }, { label: 'C', text: 'Sometimes, if a topic is trending', score: 1 }, { label: 'D', text: 'I prefer organizing school events to politics', score: 2 }] },
    // Medical
    { id: 205, tier: '12th', domain: 'medical', question: 'Studying Botany/Zoology requires massive memorization. Your take?', options: [{ label: 'A', text: 'I naturally absorb biological classification', score: 3 }, { label: 'B', text: 'I hate rote learning, I prefer logic/math', score: 0 }, { label: 'C', text: 'I use mind-maps to remember the systems', score: 2 }, { label: 'D', text: 'I only focus on human physiology', score: 2 }] },
    // Business
    { id: 206, tier: '12th', domain: 'business', question: 'Are you interested in reading about the Union Budget or Stock Markets?', options: [{ label: 'A', text: 'Yes, I track markets and financial news closely', score: 3 }, { label: 'B', text: 'No, numbers without physics bore me', score: 0 }, { label: 'C', text: 'I understand the basics of inflation/taxes', score: 2 }, { label: 'D', text: 'I find it confusing', score: 0 }] },

    // --- B.TECH (Specialization & Career Intent) ---
    // Analytical
    { id: 301, tier: 'B.Tech', domain: 'analytical', question: 'Given a choice for a semester project, you would pick:', options: [{ label: 'A', text: 'Building an ML model from scratch', score: 3 }, { label: 'B', text: 'Creating a beautifully animated frontend', score: 0 }, { label: 'C', text: 'Writing a business plan for an app', score: 0 }, { label: 'D', text: 'Designing the database architecture', score: 2 }] },
    { id: 302, tier: 'B.Tech', domain: 'analytical', question: 'When debugging a 500-line code error, you:', options: [{ label: 'A', text: 'Methodically isolate the bug using breakpoints', score: 3 }, { label: 'B', text: 'Ask ChatGPT to fix the whole file immediately', score: 1 }, { label: 'C', text: 'Get frustrated and rewrite it', score: 0 }, { label: 'D', text: 'Write a quick patch just to make it run', score: 1 }] },
    // Creativity
    { id: 303, tier: 'B.Tech', domain: 'creativity', question: 'How important is the UI/UX design in an application for you?', options: [{ label: 'A', text: 'It is everything—I spend days on CSS/Figma', score: 3 }, { label: 'B', text: 'Secondary. The backend logic is what matters', score: 0 }, { label: 'C', text: 'Important, but I use standard templates', score: 1 }, { label: 'D', text: 'I love experimenting with new animations', score: 2 }] },
    // Leadership
    { id: 304, tier: 'B.Tech', domain: 'leadership', question: 'During a hackathon, what role do you naturally fall into?', options: [{ label: 'A', text: 'Project Manager - assigning tasks and pitching', score: 3 }, { label: 'B', text: 'The sole backend programmer', score: 0 }, { label: 'C', text: 'The designer', score: 0 }, { label: 'D', text: 'The systems architect', score: 1 }] },
    // Medical
    { id: 305, tier: 'B.Tech', domain: 'medical', question: 'Would you be interested in HealthTech (like building AI for MRI scans)?', options: [{ label: 'A', text: 'Highly! Saving lives using tech is my dream', score: 3 }, { label: 'B', text: 'I prefer working on FinTech or E-commerce', score: 0 }, { label: 'C', text: 'Yes, biology data is interesting to model', score: 2 }, { label: 'D', text: 'Only if the pay is higher', score: 1 }] },
    // Business
    { id: 306, tier: 'B.Tech', domain: 'business', question: 'Do you want to pursue an MBA after your rigorous B.Tech degree?', options: [{ label: 'A', text: 'Absolutely – I want to be a Product Manager or CEO', score: 3 }, { label: 'B', text: 'No, I want to be a Principal Engineer / Architect', score: 0 }, { label: 'C', text: 'Maybe, to boost my salary later', score: 1 }, { label: 'D', text: 'I want to start my own tech startup instead', score: 3 }] }
];

module.exports = questions;