// ─────────────────────────────────────────────────────────────────────
// Job Market Intelligence Data — 30+ roles across 8 domains
// Fields: jobRole, domain, description, requiredSkills, typicalCompanies,
//         avgSalaryIndia, jobDemandScore(1-10), competitionScore(1-10),
//         riskLevel, jobOpeningFrequency, selectionProbability(%),
//         growthForecast, recommendedCourses
// ─────────────────────────────────────────────────────────────────────

const jobRoles = [
    // ──── AI / ML ────────────────────────────────────────────────────────
    {
        id: 'ml_engineer',
        jobRole: 'Machine Learning Engineer',
        domain: 'ai_ml',
        description: 'Builds & deploys ML models that power intelligent products — from recommendation systems to fraud detection.',
        requiredSkills: ['Python', 'TensorFlow/PyTorch', 'Statistics', 'SQL', 'MLOps', 'Cloud (AWS/GCP)'],
        typicalCompanies: ['Google', 'Microsoft', 'Amazon', 'NVIDIA', 'TCS', 'Infosys', 'Flipkart', 'Razorpay'],
        avgSalaryIndia: '₹8L–30L',
        jobDemandScore: 9,
        competitionScore: 7,
        riskLevel: 'Medium',
        jobOpeningFrequency: 'High',
        selectionProbability: 18,
        growthForecast: 'Very High',
        recommendedCourses: ['ML Specialization (Coursera)', 'Deep Learning (fast.ai)', 'MLOps Zoomcamp'],
    },
    {
        id: 'ai_researcher',
        jobRole: 'AI Research Scientist',
        domain: 'ai_ml',
        description: 'Conducts original research in deep learning, NLP, or robotics and publishes findings that push the field forward.',
        requiredSkills: ['Python', 'Research Methodology', 'PyTorch', 'Mathematics', 'Paper Writing', 'LLMs'],
        typicalCompanies: ['Google DeepMind', 'OpenAI', 'Meta AI', 'Microsoft Research', 'IISc', 'TIFR'],
        avgSalaryIndia: '₹15L–60L',
        jobDemandScore: 8,
        competitionScore: 9,
        riskLevel: 'High',
        jobOpeningFrequency: 'Medium',
        selectionProbability: 5,
        growthForecast: 'Exceptional',
        recommendedCourses: ['CS229 Stanford', 'Transformers (HuggingFace)', 'Research Writing'],
    },
    {
        id: 'data_scientist',
        jobRole: 'Data Scientist',
        domain: 'ai_ml',
        description: 'Extracts actionable insights from complex data using statistical models and machine learning.',
        requiredSkills: ['Python', 'R', 'SQL', 'Statistics', 'Pandas/NumPy', 'Tableau', 'ML'],
        typicalCompanies: ['Amazon', 'Walmart', 'Paytm', 'CRED', 'Meesho', 'McKinsey', 'Accenture'],
        avgSalaryIndia: '₹6L–25L',
        jobDemandScore: 9,
        competitionScore: 7,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Very High',
        selectionProbability: 22,
        growthForecast: 'Very High',
        recommendedCourses: ['IBM Data Science (Coursera)', 'Kaggle competitions', 'SQL Masterclass'],
    },
    {
        id: 'nlp_engineer',
        jobRole: 'NLP / LLM Engineer',
        domain: 'ai_ml',
        description: 'Builds language models, chatbots, and document processing systems using LLMs like GPT and BERT.',
        requiredSkills: ['Python', 'HuggingFace', 'LangChain', 'Prompt Engineering', 'RAG', 'Vector DBs'],
        typicalCompanies: ['Sarvam AI', 'Krutrim', 'Zoho', 'Freshworks', 'Uniphore', 'Vernacular.ai'],
        avgSalaryIndia: '₹10L–35L',
        jobDemandScore: 10,
        competitionScore: 6,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Very High',
        selectionProbability: 25,
        growthForecast: 'Exceptional',
        recommendedCourses: ['LangChain & Agents', 'HuggingFace NLP Course', 'Vector DBs & RAG'],
    },

    // ──── Data ───────────────────────────────────────────────────────────
    {
        id: 'data_analyst',
        jobRole: 'Data Analyst',
        domain: 'data',
        description: 'Interprets data, builds dashboards, and provides business insights to guide decision making.',
        requiredSkills: ['SQL', 'Excel', 'Power BI/Tableau', 'Python (Pandas)', 'Statistics'],
        typicalCompanies: ['Swiggy', 'Zomato', 'Byju\'s', 'Infosys', 'TCS', 'Accenture', 'PhonePe'],
        avgSalaryIndia: '₹4L–14L',
        jobDemandScore: 9,
        competitionScore: 6,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Very High',
        selectionProbability: 30,
        growthForecast: 'High',
        recommendedCourses: ['Google Data Analytics (Coursera)', 'Power BI Masterclass', 'SQL Bootcamp'],
    },
    {
        id: 'data_engineer',
        jobRole: 'Data Engineer',
        domain: 'data',
        description: 'Designs and maintains data pipelines, warehouses, and ETL systems that keep organizations data-ready.',
        requiredSkills: ['SQL', 'Python', 'Spark/Hadoop', 'Airflow', 'dbt', 'Cloud (GCP/AWS)', 'Kafka'],
        typicalCompanies: ['Uber', 'LinkedIn', 'Razorpay', 'Zepto', 'Oracle', 'Databricks', 'ThoughtWorks'],
        avgSalaryIndia: '₹7L–28L',
        jobDemandScore: 9,
        competitionScore: 6,
        riskLevel: 'Low',
        jobOpeningFrequency: 'High',
        selectionProbability: 20,
        growthForecast: 'Very High',
        recommendedCourses: ['Data Engineering Bootcamp (DataTalks)', 'dbt Fundamentals', 'Apache Spark with Scala'],
    },

    // ──── Web Dev ─────────────────────────────────────────────────────────
    {
        id: 'frontend_dev',
        jobRole: 'Frontend Developer',
        domain: 'web_dev',
        description: 'Builds the visual and interactive parts of websites and web apps using modern JS frameworks.',
        requiredSkills: ['HTML/CSS', 'JavaScript', 'React/Vue', 'TypeScript', 'Git', 'Responsive Design'],
        typicalCompanies: ['Shopify', 'Vercel', 'Razorpay', 'Swiggy', 'Zoho', 'CRED', 'Groww'],
        avgSalaryIndia: '₹4L–18L',
        jobDemandScore: 8,
        competitionScore: 7,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Very High',
        selectionProbability: 28,
        growthForecast: 'High',
        recommendedCourses: ['The Odin Project', 'React Official Docs', 'TypeScript Course (Matt Pocock)'],
    },
    {
        id: 'fullstack_dev',
        jobRole: 'Full-Stack Developer',
        domain: 'web_dev',
        description: 'Handles both frontend (React/Vue) and backend (Node/Django) development and system integration.',
        requiredSkills: ['React', 'Node.js', 'PostgreSQL/MongoDB', 'REST APIs', 'Docker', 'AWS/GCP'],
        typicalCompanies: ['Startups', 'Zepto', 'Meesho', 'Groww', 'Postman', 'Atlassian', 'Freshworks'],
        avgSalaryIndia: '₹5L–22L',
        jobDemandScore: 9,
        competitionScore: 7,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Very High',
        selectionProbability: 25,
        growthForecast: 'Very High',
        recommendedCourses: ['The Odin Project', 'MERN Stack Bootcamp', 'Docker + Kubernetes'],
    },
    {
        id: 'backend_dev',
        jobRole: 'Backend / API Engineer',
        domain: 'web_dev',
        description: 'Designs and maintains server-side APIs, databases, authentication, and scalable microservices.',
        requiredSkills: ['Node.js/Python/Java', 'REST/GraphQL', 'PostgreSQL', 'Redis', 'Docker', 'System Design'],
        typicalCompanies: ['Razorpay', 'Zerodha', 'Ola', 'Rapido', 'OYO', 'PhonePe', 'Juspay'],
        avgSalaryIndia: '₹6L–24L',
        jobDemandScore: 9,
        competitionScore: 7,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Very High',
        selectionProbability: 22,
        growthForecast: 'High',
        recommendedCourses: ['System Design (Arpit Bhayani)', 'PostgreSQL Mastery', 'Backend Engineering Bootcamp'],
    },

    // ──── UI/UX Design ────────────────────────────────────────────────────
    {
        id: 'uiux_designer',
        jobRole: 'UI/UX Designer',
        domain: 'uiux',
        description: 'Designs user interfaces, user flows, and interaction models that make digital products intuitive.',
        requiredSkills: ['Figma', 'UX Research', 'Prototyping', 'Typography', 'Usability Testing', 'Design Systems'],
        typicalCompanies: ['Swiggy', 'CRED', 'Google India', 'Meesho', 'Zomato', 'Paytm', 'Razorpay'],
        avgSalaryIndia: '₹4L–18L',
        jobDemandScore: 8,
        competitionScore: 8,
        riskLevel: 'Medium',
        jobOpeningFrequency: 'High',
        selectionProbability: 15,
        growthForecast: 'High',
        recommendedCourses: ['Google UX Design Certificate', 'Figma Master Course', 'UX Research Fundamentals'],
    },
    {
        id: 'product_designer',
        jobRole: 'Product Designer',
        domain: 'design',
        description: 'Owns the full design process from research and wireframes to polished product UI and system design.',
        requiredSkills: ['Figma', 'Design Systems', 'UX Strategy', 'Stakeholder Communication', 'Data-Driven Design'],
        typicalCompanies: ['Razorpay', 'Groww', 'BrowserStack', 'Postman', 'Freshworks', 'Adobe'],
        avgSalaryIndia: '₹7L–25L',
        jobDemandScore: 8,
        competitionScore: 7,
        riskLevel: 'Medium',
        jobOpeningFrequency: 'Medium',
        selectionProbability: 12,
        growthForecast: 'High',
        recommendedCourses: ['Advanced Figma', 'Product Design (Reforge)', 'Interaction Design Foundation'],
    },
    {
        id: 'motion_designer',
        jobRole: 'Motion / Visual Designer',
        domain: 'content',
        description: 'Creates animated graphics, video content, and visual brand assets for digital platforms.',
        requiredSkills: ['After Effects', 'Premiere Pro', 'Illustrator', 'Animation Principles', 'Brand Design'],
        typicalCompanies: ['Dream11', 'Hotstar', 'Netflix India', 'Limeroad', 'Viacom18', 'YRF'],
        avgSalaryIndia: '₹3L–12L',
        jobDemandScore: 7,
        competitionScore: 8,
        riskLevel: 'Medium',
        jobOpeningFrequency: 'Medium',
        selectionProbability: 14,
        growthForecast: 'Medium',
        recommendedCourses: ['Motion Design School', 'After Effects Masterclass', 'Visual Identity Design'],
    },

    // ──── Management / Business ───────────────────────────────────────────
    {
        id: 'product_manager',
        jobRole: 'Product Manager',
        domain: 'management',
        description: 'Owns the vision and roadmap for a product, working with engineers, designers, and business teams.',
        requiredSkills: ['Product Sense', 'Data Analysis', 'Stakeholder Management', 'PRD Writing', 'User Research'],
        typicalCompanies: ['Flipkart', 'Ola', 'Swiggy', 'Paytm', 'Google India', 'Amazon India', 'Zepto'],
        avgSalaryIndia: '₹10L–40L',
        jobDemandScore: 9,
        competitionScore: 9,
        riskLevel: 'Medium',
        jobOpeningFrequency: 'Medium',
        selectionProbability: 8,
        growthForecast: 'Very High',
        recommendedCourses: ['PM School', 'Reforge PM', 'Product Analytics (Mixpanel Academy)'],
    },
    {
        id: 'business_analyst',
        jobRole: 'Business Analyst',
        domain: 'management',
        description: 'Bridges business objectives with technology solutions by gathering requirements and analyzing data.',
        requiredSkills: ['Excel', 'SQL', 'JIRA', 'BRD Writing', 'Process Mapping', 'Stakeholder Communication'],
        typicalCompanies: ['TCS', 'Infosys', 'Wipro', 'Accenture', 'Deloitte', 'PwC', 'KPMG'],
        avgSalaryIndia: '₹5L–16L',
        jobDemandScore: 8,
        competitionScore: 6,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Very High',
        selectionProbability: 30,
        growthForecast: 'High',
        recommendedCourses: ['Business Analysis Fundamentals (IIBA)', 'Advanced Excel', 'SQL for Business'],
    },
    {
        id: 'management_consultant',
        jobRole: 'Management Consultant',
        domain: 'management',
        description: 'Solves complex business problems for client organizations through structured problem-solving frameworks.',
        requiredSkills: ['Problem Structuring', 'PowerPoint', 'Excel Modelling', 'Communication', 'Case Solving'],
        typicalCompanies: ['McKinsey', 'BCG', 'Bain', 'Deloitte', 'Kearney', 'Roland Berger', 'EY'],
        avgSalaryIndia: '₹15L–50L',
        jobDemandScore: 7,
        competitionScore: 10,
        riskLevel: 'High',
        jobOpeningFrequency: 'Low',
        selectionProbability: 3,
        growthForecast: 'Very High',
        recommendedCourses: ['Case Interview (Victor Cheng)', 'Case in Point (Book)', 'PrepLounge practice'],
    },

    // ──── Sales / Entrepreneurship ────────────────────────────────────────
    {
        id: 'growth_marketer',
        jobRole: 'Growth / Digital Marketer',
        domain: 'sales',
        description: 'Drives user acquisition and retention through SEO, paid ads, content strategy, and analytics.',
        requiredSkills: ['Google Analytics', 'Meta Ads', 'SEO', 'Email Marketing', 'A/B Testing', 'Copywriting'],
        typicalCompanies: ['Zomato', 'Nykaa', 'Cars24', 'Urban Company', 'Bewakoof', 'Mamaearth'],
        avgSalaryIndia: '₹4L–16L',
        jobDemandScore: 8,
        competitionScore: 6,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Very High',
        selectionProbability: 35,
        growthForecast: 'High',
        recommendedCourses: ['Google Digital Marketing Cert', 'Growth Hacking (Reforge)', 'HubSpot Academy'],
    },
    {
        id: 'startup_founder',
        jobRole: 'Startup Founder / Entrepreneur',
        domain: 'entrepreneurship',
        description: 'Starts and builds a new venture from idea to product-market fit, fundraising, and team building.',
        requiredSkills: ['Product Thinking', 'Sales', 'Fundraising', 'Team Building', 'Resilience', 'Networking'],
        typicalCompanies: ['Y Combinator', 'Sequoia Surge', '100X.VC', 'Antler India', 'Own Startup'],
        avgSalaryIndia: '₹0–∞ (equity-driven)',
        jobDemandScore: 6,
        competitionScore: 10,
        riskLevel: 'High',
        jobOpeningFrequency: 'N/A',
        selectionProbability: 2,
        growthForecast: 'Exceptional',
        recommendedCourses: ['YC Startup School (free)', 'The Mom Test (book)', 'iSPIRT resources'],
    },

    // ──── Govt / Finance ──────────────────────────────────────────────────
    {
        id: 'ias_officer',
        jobRole: 'IAS / Civil Services Officer',
        domain: 'govt_jobs',
        description: 'Administers public policy, leads district governance, and implements government programs across India.',
        requiredSkills: ['General Studies', 'Current Affairs', 'Essay Writing', 'CSAT', 'Interview Skills'],
        typicalCompanies: ['Government of India', 'State Governments', 'PSUs'],
        avgSalaryIndia: '₹7L–15L (+ perks)',
        jobDemandScore: 5,
        competitionScore: 10,
        riskLevel: 'High',
        jobOpeningFrequency: 'Low',
        selectionProbability: 0.5,
        growthForecast: 'Stable',
        recommendedCourses: ['Vision IAS Mains 365', 'ForumIAS resources', 'Insights IAS'],
    },
    {
        id: 'banking_officer',
        jobRole: 'Bank PO / Banking Officer',
        domain: 'finance',
        description: 'Manages banking operations, credit appraisal, and customer relationships in public/private sector banks.',
        requiredSkills: ['Quantitative Aptitude', 'Banking Awareness', 'English', 'Reasoning', 'Computer Skills'],
        typicalCompanies: ['SBI', 'PNB', 'Canara Bank', 'Bank of Baroda', 'IBPS member banks'],
        avgSalaryIndia: '₹5L–12L',
        jobDemandScore: 6,
        competitionScore: 9,
        riskLevel: 'Medium',
        jobOpeningFrequency: 'Medium',
        selectionProbability: 1,
        growthForecast: 'Stable',
        recommendedCourses: ['Adda247 IBPS PO', 'Oliveboard Mock Tests', 'Bankersadda daily GK'],
    },
    {
        id: 'ca_professional',
        jobRole: 'Chartered Accountant (CA)',
        domain: 'finance',
        description: 'Provides financial advisory, auditing, taxation, and compliance services to businesses and individuals.',
        requiredSkills: ['Accounting', 'Taxation', 'Auditing', 'Company Law', 'Financial Reporting', 'Excel'],
        typicalCompanies: ['Big 4 (Deloitte, PwC, EY, KPMG)', 'BSR & Co', 'Grant Thornton', 'Mid-size firms'],
        avgSalaryIndia: '₹7L–30L',
        jobDemandScore: 7,
        competitionScore: 8,
        riskLevel: 'Medium',
        jobOpeningFrequency: 'High',
        selectionProbability: 12,
        growthForecast: 'High',
        recommendedCourses: ['ICAI Study Material', 'CA Foundation AJ Education', 'Indirect Tax (Super20 by ICAI)'],
    },

    // ──── Research / Innovation ───────────────────────────────────────────
    {
        id: 'research_analyst',
        jobRole: 'Research Analyst',
        domain: 'research',
        description: 'Conducts primary/secondary research, market studies, or equity analysis to support strategic decisions.',
        requiredSkills: ['Data Analysis', 'Excel', 'Report Writing', 'Industry Research', 'Python (optional)', 'Economics'],
        typicalCompanies: ['Motilal Oswal', 'HDFC Securities', 'IIMs (research)', 'Think Tanks', 'McKinsey Knowledge'],
        avgSalaryIndia: '₹4L–16L',
        jobDemandScore: 7,
        competitionScore: 7,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Medium',
        selectionProbability: 18,
        growthForecast: 'Medium',
        recommendedCourses: ['Equity Research (NSE Academy)', 'Research Methodology (NPTEL)', 'CFA Level 1'],
    },
    {
        id: 'iot_engineer',
        jobRole: 'IoT / Embedded Systems Engineer',
        domain: 'hardware',
        description: 'Designs connected hardware systems — smart devices, sensors, firmware, and cloud communication.',
        requiredSkills: ['C/C++', 'Embedded C', 'Arduino/Raspberry Pi', 'MQTT', 'Microcontrollers', 'AWS IoT'],
        typicalCompanies: ['Bosch', 'Honeywell', 'L&T Technology', 'Siemens India', 'TATA Consultancy', 'HCL'],
        avgSalaryIndia: '₹4L–14L',
        jobDemandScore: 7,
        competitionScore: 5,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Medium',
        selectionProbability: 25,
        growthForecast: 'High',
        recommendedCourses: ['Embedded Systems (Coursera)', 'IoT Specialization (UC San Diego)', 'FreeRTOS Tutorial'],
    },
    {
        id: 'cybersecurity_analyst',
        jobRole: 'Cybersecurity Analyst',
        domain: 'hardware',
        description: 'Protects systems, networks, and data from cyber threats through monitoring, analysis, and incident response.',
        requiredSkills: ['Network Fundamentals', 'Linux', 'Python/Bash', 'SIEM Tools', 'Penetration Testing', 'OWASP'],
        typicalCompanies: ['CERT-IN', 'L&T Infotech', 'Wipro CyberSec', 'Palo Alto Networks', 'Crowdstrike', 'IBM Security'],
        avgSalaryIndia: '₹5L–22L',
        jobDemandScore: 9,
        competitionScore: 5,
        riskLevel: 'Low',
        jobOpeningFrequency: 'High',
        selectionProbability: 30,
        growthForecast: 'Very High',
        recommendedCourses: ['Google Cybersecurity Cert', 'CEH (EC-Council)', 'TryHackMe Labs'],
    },
    {
        id: 'cloud_architect',
        jobRole: 'Cloud/DevOps Engineer',
        domain: 'web_dev',
        description: 'Automates software delivery pipelines, manages cloud infrastructure, and ensures system reliability.',
        requiredSkills: ['AWS/GCP/Azure', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD', 'Linux', 'Python'],
        typicalCompanies: ['AWS India', 'Google Cloud', 'Microsoft Azure', 'ThoughtWorks', 'Atlassian', 'Harness'],
        avgSalaryIndia: '₹8L–30L',
        jobDemandScore: 9,
        competitionScore: 6,
        riskLevel: 'Low',
        jobOpeningFrequency: 'Very High',
        selectionProbability: 22,
        growthForecast: 'Very High',
        recommendedCourses: ['AWS Solutions Architect (Cantrill)', 'Kubernetes (CKAD)', 'Terraform Bootcamp'],
    },
];

module.exports = jobRoles;
